# Generated by Django 2.2.5 on 2019-09-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email_verified_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
