# Generated by Django 2.2.5 on 2019-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email_verified_at',
        ),
        migrations.AddField(
            model_name='users',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
